module.exports = {
  endPoint: {
    auctions: "/auctions",
    auctionsByRequest: "/auctions-by-requests",
    auctionsById: "/auctions-by-id",
    auctionParticipation: '/auction-participate',
    createContract: '/create-contract',
    createUser: '/create-user',
    createTruck: '/create-truck',
    deleteUser: '/delete-user',
    deleteTruck: '/delete-truck',
    detailRequest: "/detail-requests",
    finishSale: "/finish-sale",
    getAuctionsByStatus: '/auctions-by-status',
    getRequestBystatus: '/requests',
    getTrucksByCarrierId: '/select-truck-by-carrier',
    login: '/login',
    participateRequest: '/participate-in-request',
    requestCreation: '/create-request-and-detail',
    sales: "/sales",
    salesByStatus: "/sales-by-status",
    salesByPayType: "/sales-by-pay-type",
    salesByRequest: "/sales-by-request",
    selectProducer: '/select-producer',
    selectCarrier: '/select-carrier',
    selectUser: '/select-user',
    updateUser: '/update-user',
    updateTruck: '/update-truck',
    updateSaleState: "/update-state-sale",
    updateRequestStatus: '/update-status-request',
  },
}
