module.exports = {
  endPoint: {
    login: '/login',
    selectProducer: '/select-producer',
    selectCarrier: '/select-carrier',
    selectTruckByCarrier: '/select-truck-by-carrier',
    createuser: '/create-user',
    selectUser: '/select-user',
    updateUser: '/update-user',
    deleteUser: '/delete-user',
    createcontract: '/create-contract',
    createtruck: '/create-truck',
    deleteTruck: '/delete-truck',
    updateTruck: '/update-truck',
    getrequestbystatus: '/requests',
    participateRequest: '/participate-in-request',
    auctionparticipation: '/auction-participate',
    requestcreation: '/create-request-and-detail',
    updaterequeststatus: '/update-status-request',
  },
}
