module.exports = {
  endPoint: {
    auctions: "/auctions",
    auctionsByRequest: "/auctions-by-requests",
    auctionsById: "/auctions-by-id",
    auctionParticipation: '/auction-participate',
    createContract: '/create-contract',
    createUser: '/create-user',
    createTruck: '/create-truck',
    getCountries: '/country',
    getRequestById: '/get-requests', 
    deleteUser: '/delete-user',
    deleteTruck: '/delete-truck',
    detailRequest: "/detail-requests",
    finishSale: "/finish-sale",
    getAuctionsByStatus: '/auctions-by-status',
    getRequestBystatus: '/requests',
    getTrucksByCarrierId: '/select-truck-by-carrier',
    login: '/login',
    participateRequest: '/participate-in-request',
    requestCreation: '/create-request-and-detail',
    sales: "/sales",
    salesByStatus: "/sales-by-status",
    salesByPayType: "/sales-by-pay-type",
    salesByRequest: "/sales-by-request",
    selectProducer: '/select-producer',
    selectQualityFruit: "/select-quality-fruit",
    selectCategoryFruit: "/select-category-fruit",
    selectStatusContract: "/select-status-contract",
    selectStatusRequest: "/select-status-request",
    selectStatusAuction: "/select-status-auction",
    selectStatusSale: "/select-status-sale",
    selectFruit: "/select-fruit",
    selectTruckSize: "/select-truck-size",
    selectTruckType: "/select-truck-type",
    selectTruckType: "/select-pay-type",
    selectRequestType: "/select-request-type",
    selectUserType: "/select-user-type",
    selectUserById: "/select-user-by-id",
    selectStaticValues: "/select-static-values",
    selectCarrier: '/select-carrier',
    selectUser: '/select-user',
    updateUser: '/update-user',
    updateTruck: '/update-truck',
    updateSaleState: "/update-state-sale",
    updateRequestStatus: '/update-status-request',
  },
}


// /select-quality-fruit/1
// /select-category-fruit/1
// /select-status-contract/1
// /select-status-request/0
// /select-status-auction/1
// /select-status-sale/1
// /select-fruit/1
// /select-truck-size/1
// /select-truck-type/1
// /select-pay-type/1
// /select-request-type/1
// /select-user-type/1
// /select-static-values/1